import { Package2 } from "lucide-react"

export default function OperationPrintView({ op }: { op: any }) {
  if (!op) return null

  return (
    <div className="hidden print:block p-8 bg-white text-black font-sans">
      <div className="flex justify-between items-start border-b pb-6 mb-6">
        <div className="flex items-center gap-2">
          <div className="flex aspect-square size-10 items-center justify-center rounded-lg bg-black text-white">
            <Package2 className="size-6" />
          </div>
          <span className="text-2xl font-bold font-heading">StockSense</span>
        </div>
        <div className="text-right">
          <h1 className="text-3xl font-bold uppercase text-gray-800">{op.type}</h1>
          <p className="text-xl font-medium mt-1">{op.reference}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div>
          <h3 className="font-semibold text-gray-500 mb-2 uppercase text-sm tracking-wider">Details</h3>
          <p className="mb-1"><span className="font-medium inline-block w-24">Date:</span> {new Date(op.scheduleDate).toLocaleDateString()}</p>
          <p className="mb-1"><span className="font-medium inline-block w-24">Status:</span> {op.status}</p>
          <p className="mb-1"><span className="font-medium inline-block w-24">Responsible:</span> {op.responsible?.fullName || 'N/A'}</p>
        </div>
        <div>
          <h3 className="font-semibold text-gray-500 mb-2 uppercase text-sm tracking-wider">Locations & Contact</h3>
          {(op.type === 'RECEIPT' || op.type === 'DELIVERY') && (
            <p className="mb-1"><span className="font-medium inline-block w-24">Contact:</span> {op.contact?.name || 'N/A'}</p>
          )}
          {op.type !== 'RECEIPT' && op.type !== 'ADJUSTMENT' && (
            <p className="mb-1"><span className="font-medium inline-block w-24">From:</span> {op.sourceLocation?.name || 'N/A'}</p>
          )}
          {op.type !== 'DELIVERY' && (
            <p className="mb-1"><span className="font-medium inline-block w-24">To:</span> {op.destLocation?.name || 'N/A'}</p>
          )}
        </div>
      </div>

      <div className="mb-8">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b-2 border-gray-300">
              <th className="py-3 px-2 font-semibold text-gray-700">Product</th>
              <th className="py-3 px-2 font-semibold text-gray-700 text-right w-32">Demand</th>
              <th className="py-3 px-2 font-semibold text-gray-700 text-right w-32">Done</th>
            </tr>
          </thead>
          <tbody>
            {op.lines?.map((line: any, idx: number) => (
              <tr key={idx} className="border-b border-gray-200">
                <td className="py-3 px-2">{line.product?.name || 'Unknown Product'}</td>
                <td className="py-3 px-2 text-right">{line.quantity}</td>
                <td className="py-3 px-2 text-right">{line.countedQuantity ?? 0}</td>
              </tr>
            ))}
            {(!op.lines || op.lines.length === 0) && (
              <tr>
                <td colSpan={3} className="py-8 text-center text-gray-500 italic">
                  No products in this operation.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <div className="mt-16 text-center text-sm text-gray-400">
        <p>Generated by StockSense ERP</p>
      </div>
    </div>
  )
}
